//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDemoConsumer.ServiceReferenceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Input", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Input : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTest.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Sum", ReplyAction="http://tempuri.org/ITestService/SumResponse")]
        int Sum(WcfDemoConsumer.ServiceReferenceTest.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Sum", ReplyAction="http://tempuri.org/ITestService/SumResponse")]
        System.Threading.Tasks.Task<int> SumAsync(WcfDemoConsumer.ServiceReferenceTest.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Substrqact", ReplyAction="http://tempuri.org/ITestService/SubstrqactResponse")]
        int Substrqact(WcfDemoConsumer.ServiceReferenceTest.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/Substrqact", ReplyAction="http://tempuri.org/ITestService/SubstrqactResponse")]
        System.Threading.Tasks.Task<int> SubstrqactAsync(WcfDemoConsumer.ServiceReferenceTest.Input input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : WcfDemoConsumer.ServiceReferenceTest.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<WcfDemoConsumer.ServiceReferenceTest.ITestService>, WcfDemoConsumer.ServiceReferenceTest.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(WcfDemoConsumer.ServiceReferenceTest.Input input) {
            return base.Channel.Sum(input);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(WcfDemoConsumer.ServiceReferenceTest.Input input) {
            return base.Channel.SumAsync(input);
        }
        
        public int Substrqact(WcfDemoConsumer.ServiceReferenceTest.Input input) {
            return base.Channel.Substrqact(input);
        }
        
        public System.Threading.Tasks.Task<int> SubstrqactAsync(WcfDemoConsumer.ServiceReferenceTest.Input input) {
            return base.Channel.SubstrqactAsync(input);
        }
    }
}
